name: reckomov_app
description: "Recommendation movie project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  http: ^1.1.0
  get: ^4.6.6
  cached_network_image: ^3.3.0
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  flutter_staggered_animations: ^1.0.0
  shimmer: ^2.0.0
  internet_connection_checker_plus: ^2.5.2
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-light.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Semibold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"
